language: node_js

node_js:
  - "6"

os:
  - osx

env:
  - TARGET_ARCH=x64

osx_image: xcode7.3

addons:
  apt:
    packages:
      - xvfb

before_install:
  - export DISPLAY=:99.0
  - Xvfb :99 -screen 0 1440x900x24 > /dev/null 2>&1 &

install:
  - nvm install 6
  - npm install
  - npm prune
  - npm install -g bower
  - bower install --allow-root
  - bower prune

script:
  - npm test
